apiVersion: v1
kind: Namespace
metadata:
  name: llm
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"Key": "kubernetes.azure.com/scalesetpriority", "Operator": "Equal", "Value": "spot", "Effect": "NoSchedule"}, {"Key": "sku", "Operator": "Equal", "Value": "gpu", "Effect": "NoSchedule"}]'
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vllm
  name: vllm
  namespace: llm
spec:
  selector:
    matchLabels:
      app: vllm
  serviceName: vllm
  replicas: 2
  template:
    metadata:
      labels:
        app: vllm
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - vllm
            topologyKey: "kubernetes.io/hostname"    
      containers:
      - image: ghcr.io/huangyingting/inference-images-vllm:main
        imagePullPolicy: Always
        name: vllm
        resources:
          limits:
           nvidia.com/gpu: 1        
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP        
        volumeMounts:
        - name: shm
          mountPath: /dev/shm        
        - name: vllm
          mountPath: "/data"
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: vllm
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-csi-premium
      resources:
        requests:
          storage: 16Gi      
---
apiVersion: v1
kind: Service
metadata:
  name: vllm
  namespace: llm
  labels:
    app: vllm
spec:
  ports:
  - port: 8080
    targetPort: 8000
  selector:
    app: vllm